### PR TITLE
Upgdate hof-template-partials to v4.3.0

### PR DESCRIPTION
**Pull request by sulthan-ahmed**
Includes the new error summary, `There is a problem`

### CODE REVIEW

**Review by zuzak — COMMENTED** [review]
I'm not convinced this is a required change, but it won't do any harm
`^4.2.0` matches `4.3.0` (or, rather, whichever `4.x.x` is highest)

might want to `git commit --amend && git push origin +update/hof-template-partials-v4.3.0` to fix the typo in the commit message though

**Comment by sulthan-ahmed** [comment]
@zuzak I agree in principle it shouldn't matter, but it matters when we run the app, see screenshot.

Screenshot 2019-06-27 at 16 05 10

Thanks, I've now updated the commit

**Comment by jjrobothamho** [comment]
Looks good to me

**Comment by sulthan-ahmed** [comment]
merged as Julian has approved it

**Pull request merged**
